### ISSUE TITLE
請問有支援solr 4.6.0嗎?

### ISSUE THREAD

**Issue by jimlingandy** [lgnlgn/ansj4solr#1]

**Comment by lgnlgn** [comment]
抱歉這麼久才看到，目前還沒提供，但是不難做到，你只要POM依賴改成4.6看下哪裡飄紅改改相應的源碼就可以了。

**Comment by jimlingandy** [comment]
真是太感謝了，謝謝提供資訊。
2014/3/2 下午10:14 於 "Guoning Liang" notifications@github.com 寫道：
